import tkinter as tk
from quiz_app_data_loader import QuizDataLoader
from quiz_app_logic import QuizLogic
from quiz_app_question_display import QuestionDisplay
from quiz_app_answer_buttons import AnswerButtons
from quiz_app_feedback import FeedbackPanel